<a href="https://colab.research.google.com/github/thejunghare/ml-mz/blob/main/numpy_pandas_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# first_name = "mark"
# print(first_name)


nums = [1,2,4,5,6]

for x in nums:
  print(x * 2)

print(nums)

2
4
8
10
12
[1, 2, 4, 5, 6]


In [ ]:
import numpy as np

In [ ]:
arr = np.array(1) # basic array in numpy
arr1 = np.array([1,2,3,4,5,6,7,8,8])
print(arr1)

# some maths
print(arr1 * 2)

# access elements
print(arr1[1]) # 2

# slice
print(arr1[1:4]) # 2,3,4
print(arr1[:4]) #  1,2,3,4
print(arr1[3:])
print(arr1[1:6:2]) #2, 4, 6
print(arr1[:-1]) #  1- 7
print(arr1[-1:]) # 8


arr2 = np.array([[1,2,3,4], [5,6,7,8]])
print(arr2[1,0])

print(arr2[1, : 3])

[1 2 3 4 5 6 7 8 8]
[ 2  4  6  8 10 12 14 16 16]
2
[2 3 4]
[1 2 3 4]
[4 5 6 7 8 8]
[2 4 6]
[1 2 3 4 5 6 7 8]
[8]
5
[5 6 7]


In [ ]:
# mean
arr1_mean = np.mean(arr1)
# median
arr1_median = np.median(arr1)
# mode
arr1_mode = np.unique(arr1)
# std
arr1_std = np.std(arr1)
print(arr1_mean, arr1_median, arr1_mode, arr1_std)

4.888888888888889 5.0 [1 2 3 4 5 6 7 8] 2.4241582476968255


In [ ]:
import pandas as pd

In [ ]:
data = {
    'students': ["a", "b", "c", "d"],
    'marks': [10, 20, 30, None],
    'div': ['A', 'B', 'D', None]
}


df = pd.DataFrame(data)

# replace
# df = df.fillna(50)


# drop
# df = df.dropna()

# df = df.count()

df = df.isnull().sum()
print(df)

students    0
marks       1
div         1
dtype: int64
